apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: training-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 22.0.0
    chart: kafka
    helm:
      valuesFrom:
        - name: my-secrets
      plugin:
        name: sops
      values: |
        replicaCount: 1
        externalAccess:
          enabled: false
        service:
          type: LoadBalancer
          loadBalancerIP: secrets.staticIP
        auth:
          clientPassword: null
          jmxPassword: null
          zookeeperPassword: null
  destination:
    server: secrets.destinationServer
    namespace: kafka
  syncPolicy:
    automated: {}
